use_frameworks!

platform :ios, '13.0'

target 'WepinPin_Example' do
  # pod 'WepinCommon', :path => '../../WepinCommon'
  # pod 'WepinCore', :path => '../../WepinCore'
  # pod 'WepinModal', :path => '../../WepinModal'
  # pod 'WepinLogin', :path => '../../WepinLogin'
  pod 'WepinCommon', 'WepinCommon', '~> 1.1.2'
  pod 'WepinCore', 'WepinCommon', '~> 1.1.2'
  pod 'WepinModal', 'WepinCommon', '~> 1.1.2'
  pod 'WepinLogin', 'WepinCommon', '~> 1.1.2'
  # pod 'WepinPin', :path => '../'
  pod 'WepinPin', '~> 1.1.2'

  target 'WepinPin_Tests' do
    inherit! :search_paths

    
  end
end
