use_frameworks!

platform :ios, '13.0'

target 'WepinPin_Example' do
  # pod 'WepinCommon', :path => '../../WepinCommon'
  # pod 'WepinCore', :path => '../../WepinCore'
  # pod 'WepinModal', :path => '../../WepinModal'
  # pod 'WepinLogin', :path => '../../WepinLogin'
  pod 'WepinCommon', '~> 1.2.1'
  pod 'WepinCore', '~> 1.2.1'
  pod 'WepinModal', '~> 1.2.1'
  pod 'WepinLogin', '~> 1.2.1'
#  pod 'WepinPin', :path => '../'
  pod 'WepinPin', '~> 1.2.1'

  target 'WepinPin_Tests' do
    inherit! :search_paths

    
  end
end
